description: Out-of-bound access in f2fs_iget() when mounting a corrupted f2fs image
references:
- https://bugzilla.kernel.org/show_bug.cgi?id=200173
- https://git.kernel.org/pub/scm/linux/kernel/git/chao/linux.git/commit/?h=f2fs-dev&id=190286a242344d42aad83c8e70169d6d72a63d05
fixed-by:
  linux-4.18.y: [b6f493453c78311598fdd204f7815e683818512a]
  mainline: [76d56d4ab4f2a9e4f085c7d77172194ddaccf7d2]
