description: |-
  In the Lustre file system before 2.12.3, the ptlrpc module has an
  out-of-bounds access and panic due to the lack of validation for specific
  fields of packets sent by a client. In the function
  ldlm_cancel_hpreq_check, there is no lock_count bounds check.
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20426
- http://lustre.org/
- http://wiki.lustre.org/Lustre_2.12.3_Changelog
- https://jira.whamcloud.com/browse/LU-12614
- https://review.whamcloud.com/#/c/36107/
comments:
  Ubuntu-cascardo: |-
    The affected code was never part of linux, as the staging driver
      was only the client side.
  Ubuntu-sbeattie: |-
    lustre was removed from the upstream staging tree in 4.18
      (be65f9ed267fd7d8b3146b7c4be9ecdd3e0aa3ed)
  wens: |-
    Lustre file system was added to staging in v3.11 and removed in v4.18.
    Confirmed the code path in question does not exist in the staging driver.
introduced-by:
  mainline: never
