description: 'ASoC: ops: Check bounds for second channel in snd_soc_put_volsw_sx()'
references:
- https://www.cve.org/CVERecord?id=CVE-2022-48951
- https://git.kernel.org/stable/c/56288987843c3cb343e81e5fa51549cbaf541bd0
- https://git.kernel.org/stable/c/cf1c225f1927891ae388562b78ced7840c3723b9
- https://git.kernel.org/stable/c/18a168d85eadcfd45f015b5ecd2a97801b959e43
- https://git.kernel.org/stable/c/9796d07c753164b7e6b0d7ef23fb4482840a9ef8
- https://git.kernel.org/stable/c/50b5f6d4d9d2d69a7498c44fd8b26e13d73d3d98
- https://git.kernel.org/stable/c/cf611d786796ec33da09d8c83d7d7f4e557b27de
- https://git.kernel.org/stable/c/1798b62d642e7b3d4ea3403914c3caf4e438465d
- https://git.kernel.org/stable/c/97eea946b93961fffd29448dcda7398d0d51c4b2
- https://lore.kernel.org/linux-cve-announce/2024102141-CVE-2022-48951-da5f@gregkh/
- https://git.kernel.org/linus/97eea946b93961fffd29448dcda7398d0d51c4b2
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v6.1-rc8.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [18a168d85eadcfd45f015b5ecd2a97801b959e43]
  cip/4.19-rt: [18a168d85eadcfd45f015b5ecd2a97801b959e43]
  cip/4.4: [acf37a15557b31506b1881617bd17a574627719f]
  cip/4.4-rt: [acf37a15557b31506b1881617bd17a574627719f]
  cip/4.4-st: [acf37a15557b31506b1881617bd17a574627719f]
  cip/5.10: [50b5f6d4d9d2d69a7498c44fd8b26e13d73d3d98]
  cip/5.10-rt: [50b5f6d4d9d2d69a7498c44fd8b26e13d73d3d98]
  mainline: [97eea946b93961fffd29448dcda7398d0d51c4b2]
  stable/4.19: [18a168d85eadcfd45f015b5ecd2a97801b959e43]
  stable/5.10: [50b5f6d4d9d2d69a7498c44fd8b26e13d73d3d98]
  stable/5.15: [cf611d786796ec33da09d8c83d7d7f4e557b27de]
  stable/5.4: [9796d07c753164b7e6b0d7ef23fb4482840a9ef8]
  ubuntu/bionic: [203e94d4f5870ed575174b66e5384cad94bca6be]
  ubuntu/focal: [4c5e28dee40f16e736d0937f940c69540c5c09e5]
