description: 'ASoC: ops: Reject out of bounds values in snd_soc_put_volsw()'
references:
- https://www.cve.org/CVERecord?id=CVE-2022-48738
- https://git.kernel.org/linus/817f7c9335ec01e0f5e8caffc4f1dcd5e458a4c0
- https://git.kernel.org/stable/c/40f598698129b5ceaf31012f9501b775c7b6e57d
- https://git.kernel.org/stable/c/586ef863c94354a7e00e5ae5ef01443d1dc99bc7
- https://git.kernel.org/stable/c/65a61b1f56f5386486757930069fbdce94af08bf
- https://git.kernel.org/stable/c/68fd718724284788fc5f379e0b7cac541429ece7
- https://git.kernel.org/stable/c/a9394f21fba027147bf275b083c77955864c366a
- https://git.kernel.org/stable/c/9e8895f1b3d4433f6d78aa6578e9db61ca6e6830
- https://git.kernel.org/stable/c/bb72d2dda85564c66d909108ea6903937a41679d
- https://git.kernel.org/stable/c/817f7c9335ec01e0f5e8caffc4f1dcd5e458a4c0
- https://lore.kernel.org/linux-cve-announce/2024062001-CVE-2022-48738-ecf0@gregkh/
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.17-rc3.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [65a61b1f56f5386486757930069fbdce94af08bf]
  cip/4.19-rt: [65a61b1f56f5386486757930069fbdce94af08bf]
  cip/4.4: [86ad5e66a4c50aa415e9c3e0ba5cc8bd023708d2]
  cip/4.4-rt: [86ad5e66a4c50aa415e9c3e0ba5cc8bd023708d2]
  cip/4.4-st: [86ad5e66a4c50aa415e9c3e0ba5cc8bd023708d2]
  cip/5.10: [a9394f21fba027147bf275b083c77955864c366a]
  cip/5.10-rt: [a9394f21fba027147bf275b083c77955864c366a]
  debian/buster-security: ['version:debian/4.19.232-1']
  mainline: [817f7c9335ec01e0f5e8caffc4f1dcd5e458a4c0]
  stable/4.19: [65a61b1f56f5386486757930069fbdce94af08bf]
  stable/5.10: [a9394f21fba027147bf275b083c77955864c366a]
  stable/5.15: [9e8895f1b3d4433f6d78aa6578e9db61ca6e6830]
  stable/5.4: [68fd718724284788fc5f379e0b7cac541429ece7]
  ubuntu/bionic: [1249113450d506e80e305cb8bc272723da7b54b7]
  ubuntu/focal: [35180435fe649f7805b77c5de9653df4f21cb2d7]
