description: 'sched/rt: pick_next_rt_entity(): check list_entry'
references:
- https://bugzilla.redhat.com/show_bug.cgi?id=2173436
- https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7c4a5b89a0b5a57a64b601775b296abf77a9fe97
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-1077
- https://git.kernel.org/linus/7c4a5b89a0b5a57a64b601775b296abf77a9fe97
- https://seclists.org/oss-sec/2023/q1/126
- https://bugzilla.suse.com/show_bug.cgi?id=1208600
- https://ubuntu.com/security/notices/USN-6033-1
- https://ubuntu.com/security/notices/USN-6171-1
- https://ubuntu.com/security/notices/USN-6172-1
- https://ubuntu.com/security/notices/USN-6185-1
- https://ubuntu.com/security/notices/USN-6187-1
- https://ubuntu.com/security/notices/USN-6207-1
- https://ubuntu.com/security/notices/USN-6222-1
- https://ubuntu.com/security/notices/USN-6223-1
comments:
  debian/carnil: 'Commit fixes 326587b84078 ("sched: fix goto retry in pick_next_task_rt()")'
  masami: 'Introduced by commit 326587b ("sched: fix goto retry in pick_next_task_rt()")
    in 2.6.25-rc1.'
introduced-by:
  mainline: [326587b840785c60f5dc18557235a23bafefd620]
fixed-by:
  cip/5.10: [80a1751730b302d8ab63a084b2fa52c820ad0273]
  cip/5.10-rt: [80a1751730b302d8ab63a084b2fa52c820ad0273]
  cip/6.1: [6b4fcc4e8a3016e85766c161daf0732fca16c3a3]
  mainline: [7c4a5b89a0b5a57a64b601775b296abf77a9fe97]
  stable/5.10: [80a1751730b302d8ab63a084b2fa52c820ad0273]
  stable/5.15: [2c36c390a74981d03f04f01fe7ee9c3ac3ea11f7]
  stable/5.4: [084cd75643b61fb924f70cba98a71dea14942938]
  stable/6.1: [6b4fcc4e8a3016e85766c161daf0732fca16c3a3]
  stable/6.2: [1099004ae1664703ec573fc4c61ffb24144bcb63]
  ubuntu/focal: [ac5b28ba778f78dfc4b86655c59b0aa2e4f60045]
