description: 'io_uring: fail cancellation for EXITING tasks'
references:
- https://www.cve.org/CVERecord?id=CVE-2021-47569
- https://git.kernel.org/stable/c/3d2a1e68fd9904fdc1b02f2e7d40ca47df7ba39f
- https://git.kernel.org/stable/c/617a89484debcd4e7999796d693cf0b77d2519de
- https://lore.kernel.org/linux-cve-announce/2024052453-CVE-2021-47569-2d3a@gregkh/
- https://git.kernel.org/linus/617a89484debcd4e7999796d693cf0b77d2519de
comments:
  cip/cip-kernel-sec: |-
    Introduced by commit 89b263f ("io_uring: run linked timeouts from task_work") in v5.15-rc1.
    Fixed in v5.16-rc3.
  debian/carnil: |-
    Introduced in 89b263f6d56e6 ("io_uring: run linked timeouts from task_work").
    Vulnerable versions: 5.15-rc1.
introduced-by:
  mainline: [89b263f6d56e683ddcf7643140271ef6e36c72b9]
fixed-by:
  mainline: [617a89484debcd4e7999796d693cf0b77d2519de]
  stable/5.15: [3d2a1e68fd9904fdc1b02f2e7d40ca47df7ba39f]
  ubuntu/focal: ['version:5.4.0-9.12']
