description: 'ceph: prevent use-after-free in encode_cap_msg()'
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-26689
- https://git.kernel.org/stable/c/8180d0c27b93a6eb60da1b08ea079e3926328214
- https://git.kernel.org/stable/c/70e329b440762390258a6fe8c0de93c9fdd56c77
- https://git.kernel.org/stable/c/f3f98d7d84b31828004545e29fd7262b9f444139
- https://git.kernel.org/stable/c/ae20db45e482303a20e56f2db667a9d9c54ac7e7
- https://git.kernel.org/stable/c/7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc
- https://git.kernel.org/stable/c/cda4672da1c26835dcbd7aec2bfed954eda9b5ef
- https://lore.kernel.org/linux-cve-announce/2024040336-CVE-2024-26689-990b@gregkh/
comments:
  cip/cip-kernel-sec: Introduced commit is not determined.Fixed in v6.8-rc4.
  cip/masami: |-
    Commit 0a454bdd ("ceph: reorganize __send_cap for less spinlock abuse") in
    5.8-rc1 introduced the __prep_cap(). It seems as if this commit introduced 
    this bug.
  debian/carnil: First introducing commit could not be determined.
introduced-by:
  mainline: [0a454bdd501ad1aa30bb72e9581efa338ad6ce5c]
fixed-by:
  cip/5.10: [8180d0c27b93a6eb60da1b08ea079e3926328214]
  cip/6.1: [f3f98d7d84b31828004545e29fd7262b9f444139]
  cip/6.1-rt: [f3f98d7d84b31828004545e29fd7262b9f444139]
  mainline: [cda4672da1c26835dcbd7aec2bfed954eda9b5ef]
  stable/5.10: [8180d0c27b93a6eb60da1b08ea079e3926328214]
  stable/5.15: [70e329b440762390258a6fe8c0de93c9fdd56c77]
  stable/6.1: [f3f98d7d84b31828004545e29fd7262b9f444139]
  stable/6.6: [ae20db45e482303a20e56f2db667a9d9c54ac7e7]
  stable/6.7: [7958c1bf5b03c6f1f58e724dbdec93f8f60b96fc]
