description: Out of bounds memory access bug in get_next_net_page() in fs/f2fs/node.c
references:
- https://www.openwall.com/lists/oss-security/2021/03/28/2
- https://bugzilla.redhat.com/show_bug.cgi?id=1944298
- https://lore.kernel.org/lkml/20210322114730.71103-1-yuchao0@huawei.com/
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3506
- https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2520013.html
- https://ubuntu.com/security/notices/USN-4997-1
- https://ubuntu.com/security/notices/USN-5000-1
- https://ubuntu.com/security/notices/USN-5001-1
- https://ubuntu.com/security/notices/USN-5016-1
- https://ubuntu.com/security/notices/USN-5000-2
- https://ubuntu.com/security/notices/USN-4997-2
- https://ubuntu.com/security/notices/USN-5339-1
- https://ubuntu.com/security/notices/USN-5343-1
- https://www.cve.org/CVERecord?id=CVE-2021-3506
comments:
  debian/bwh: Appears to have been introduced before 4.9.
  wens: Introduced in v3.8-rc1; fix queued up in -next for 5.14.
introduced-by:
  mainline: [e05df3b115e7308afbca652769b54e4549fcc723]
fixed-by:
  cip/4.19: [bfa08a47cea2a9fab077c7135b9cfdf04e69c67a]
  cip/4.19-rt: [bfa08a47cea2a9fab077c7135b9cfdf04e69c67a]
  cip/5.10: [9aa4602237d535b83c579eb752e8fc1c3e7e7055]
  cip/5.10-rt: [9aa4602237d535b83c579eb752e8fc1c3e7e7055]
  debian/buster-security: ['version:debian/4.19.194-1']
  mainline: [b862676e371715456c9dade7990c8004996d0d9e]
  stable/4.19: [bfa08a47cea2a9fab077c7135b9cfdf04e69c67a]
  stable/5.10: [9aa4602237d535b83c579eb752e8fc1c3e7e7055]
  stable/5.11: [7fe4c47161c21f3b1c3581c2653147281ca0e4fa]
  stable/5.12: [0b60f23e29c8dfcf1b8a037fae1167e4f2e3249e]
  stable/5.4: [27a130638406815eba083c632ee083f0c5e688c2]
  ubuntu/bionic: [2136c433059d21141a8e1b2a04fc1916f94f4a9d]
  ubuntu/focal: [f27df12902535de063e9ba3211167995cb960243]
  ubuntu/groovy: [47d7a09ce0669547de3a46b139fd77462dc7aed0]
ignore:
  cip/4.19-rt: No member enables F2FS
  cip/4.4-rt: No member enables F2FS
  debian/stretch-security: f2fs is not supportable
