description: 'ocfs2: add bounds checking to ocfs2_xattr_find_entry()'
references:
- https://www.cve.org/CVERecord?id=CVE-2024-47670
- https://git.kernel.org/stable/c/9b32539590a8e6400ac2f6e7cf9cbb8e08711a2f
- https://git.kernel.org/stable/c/1f6e167d6753fe3ea493cdc7f7de8d03147a4d39
- https://git.kernel.org/stable/c/8e7bef408261746c160853fc27df3139659f5f77
- https://git.kernel.org/stable/c/9e3041fecdc8f78a5900c3aa51d3d756e73264d6
- https://lore.kernel.org/linux-cve-announce/2024100919-CVE-2024-47670-53f3@gregkh/
- https://git.kernel.org/stable/c/b49a786beb11ff740cb9e0c20b999c2a0e1729c2
- https://git.kernel.org/stable/c/60c0d36189bad58b1a8e69af8781d90009559ea1
- https://git.kernel.org/stable/c/34759b7e4493d7337cbc414c132cef378c492a2c
- https://git.kernel.org/stable/c/5bbe51eaf01a5dd6fb3f0dea81791e5dbc6dc6dd
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v6.11-rc1.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [b49a786beb11ff740cb9e0c20b999c2a0e1729c2]
  cip/5.10: [34759b7e4493d7337cbc414c132cef378c492a2c]
  cip/6.1: [9b32539590a8e6400ac2f6e7cf9cbb8e08711a2f]
  cip/6.1-rt: [9b32539590a8e6400ac2f6e7cf9cbb8e08711a2f]
  mainline: [9e3041fecdc8f78a5900c3aa51d3d756e73264d6]
  stable/4.19: [b49a786beb11ff740cb9e0c20b999c2a0e1729c2]
  stable/5.10: [34759b7e4493d7337cbc414c132cef378c492a2c]
  stable/5.15: [5bbe51eaf01a5dd6fb3f0dea81791e5dbc6dc6dd]
  stable/5.4: [60c0d36189bad58b1a8e69af8781d90009559ea1]
  stable/6.1: [9b32539590a8e6400ac2f6e7cf9cbb8e08711a2f]
  stable/6.10: [8e7bef408261746c160853fc27df3139659f5f77]
  stable/6.6: [1f6e167d6753fe3ea493cdc7f7de8d03147a4d39]
