description: A bug was found in the usb_giveback_urb function causes DoS.
references:
- https://bugzilla.redhat.com/show_bug.cgi?id=2227726
- https://github.com/wanrenmi/a-usb-kernel-bug
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4010
- https://access.redhat.com/security/cve/CVE-2023-4010
- https://bugzilla.suse.com/show_bug.cgi?id=1214030
- https://github.com/wanrenmi/a-usb-kernel-bug/issues/1
- https://www.cve.org/CVERecord?id=CVE-2023-4010
comments:
  debian/bwh: |-
    This might be related to commit 26c6c2f8a907 "USB: HCD: Fix URB
    giveback issue in tasklet function" but I have not investigated
    that.
  ubuntu/magalilemes: |-
    This is a USB device using interrupt transfers. So,
     as soon as a response is received, it submits another URB, waiting
     for the next "interrupt" to happen. That is totally normal. But
     as the response is malformed, the imon driver outputs a warning
     without any throttling. There is no system lockup happening. The
     imon driver has been issuing those warnings since its inception,
     so using that as the break commit.
  ubuntu/sbeattie: |-
    issue is not clear; the function the reporter mentions
      does not exist. though there is the similar usb_giveback_urb_bh().
      However, as of 6.3.7, which the reporter claims is vulnerable,
      that function contained no gotos, though it did until 26c6c2f8a907
      ("USB: HCD: Fix URB giveback issue in tasklet function"), which
      landed in v6.0-rc1.
introduced-by:
  mainline: [21677cfc562a27e099719d413287bc8d1d24deb7]
