description: 'ceph: fix inode leak on getattr error in __fh_to_dentry'
references:
- https://lore.kernel.org/linux-cve-announce/2024022828-CVE-2021-47000-981a@gregkh/T/#u
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-47000
- https://git.kernel.org/linus/1775c7ddacfcea29051c67409087578f8f4d751b
- https://git.kernel.org/stable/c/2ad8af2b70e986284050213230428b823b950a38
- https://git.kernel.org/stable/c/bf45c9fe99aa8003d2703f1bd353f956dea47e40
- https://git.kernel.org/stable/c/22fa4c8288f1ec40f6d62d7a32c57ac176f9f0bc
- https://git.kernel.org/stable/c/0a219432127d396120fc88cabd82785e0ff72a2f
- https://git.kernel.org/stable/c/1775c7ddacfcea29051c67409087578f8f4d751b
- https://www.cve.org/CVERecord?id=CVE-2021-47000
comments:
  debian/carnil: |-
    Introduced in 878dabb64117 ("ceph: don't return -ESTALE if there's still an
    open file"). Vulnerable versions: 5.4.49 5.7.6 5.8-rc1.
  masami: "Introduced by commit 878dabb (\"ceph: don't return -ESTALE if there's still\
    \ \nan open file\") in 5.8-rc1. This commit is backported to 5.4 Linux 4.x is\
    \ \nnot affected. Fixed in 5.13-rc1."
introduced-by:
  mainline: [878dabb64117406abd40977b87544d05bb3031fc]
  stable/5.4: [807460787179dee5f74906965eeb5f3ca2353992]
  ubuntu/focal: [4601c80673b1d727f66463cb8b39fd912377bbf0]
fixed-by:
  cip/5.10: [bf45c9fe99aa8003d2703f1bd353f956dea47e40]
  cip/5.10-rt: [bf45c9fe99aa8003d2703f1bd353f956dea47e40]
  mainline: [1775c7ddacfcea29051c67409087578f8f4d751b]
  stable/5.10: [bf45c9fe99aa8003d2703f1bd353f956dea47e40]
  stable/5.4: [2ad8af2b70e986284050213230428b823b950a38]
  ubuntu/focal: [0ae5e5b63ee6fb43628bb67e4629ec257aafbed7]
  ubuntu/groovy: [9f32c37e7754cb53b60e6c8ef3479b7e58d7204c]
